<a href="https://colab.research.google.com/github/fabioeomedeiros/Data-Science-Base/blob/main/01_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Biblioteca Numpy

In [ ]:
import numpy as np
A = np.array([1,2,3])
print(A)
print(type(A))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
B = np.array([[0,5,7], [11,6,5], [9,4,1]])
print(B)
print(type(B))

[[ 0  5  7]
 [11  6  5]
 [ 9  4  1]]
<class 'numpy.ndarray'>


### Matriz de zeros

In [ ]:
C = np.zeros((3,4))
print(C)
print(type(C))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>


### Matriz identidade

In [ ]:
I = np.eye(10)
print(I)
print(type(I))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>


### Métodos em Arrays

In [ ]:
print("B = ")
print(B)
print()
print(f"Maior = {B.max()}") #Maior elemento do Array
print(f"Menor = {B.min()}") #Menor elemento do Array
print(f"Soma = {B.sum()}") #Soma dos elementos do array
print(f"Média = {B.mean():.2f}") #Média dos elementos do array
print(f"Desvio Padrão = {B.std():.2f}") #Desvio padrão dos elementos do array



B = 
[[ 0  5  7]
 [11  6  5]
 [ 9  4  1]]

Maior = 11
Menor = 0
Soma = 48
Média = 5.33
Desvio Padrão = 3.30
