<a href="https://colab.research.google.com/github/fabioeomedeiros/Data-Science-Base/blob/main/03_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Biblioteca Pandas

In [ ]:
import pandas as pd
import numpy as np


alunos = {'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos'],
          'Notas': [4.2, 7.8, 5.5, 9.0],
          'Aprovado': ['N', 'S', 'N', 'S']}

print(alunos)

{'Nome': ['Ricardo', 'Pedro', 'Roberto', 'Carlos'], 'Notas': [4.2, 7.8, 5.5, 9.0], 'Aprovado': ['N', 'S', 'N', 'S']}


### Data Frame

In [ ]:
DF_alunos = pd.DataFrame(alunos)
print(DF_alunos)

      Nome  Notas Aprovado
0  Ricardo    4.2        N
1    Pedro    7.8        S
2  Roberto    5.5        N
3   Carlos    9.0        S


### Séreis

In [ ]:
objeto1 = pd.Series([7, 5, 9, 17, 19])
print(objeto1)

0     7
1     5
2     9
3    17
4    19
dtype: int64


In [ ]:
AR_vetor1 = np.array([7, 5, 9, 17, 19])
AR_vetor2 = np.array([[7, 5, 9, 17, 19], [19, 17, 5, 9, 7]])
print(AR_vetor1)
print(AR_vetor2)

[ 7  5  9 17 19]
[[ 7  5  9 17 19]
 [19 17  5  9  7]]


In [ ]:
objeto2 = pd.Series(AR_vetor1)
print(objeto2)

0     7
1     5
2     9
3    17
4    19
dtype: int64
